#! /bin/bash

# Install BLAST & MagicBLAST packages
curl -o magicblast.tar.gz https://ftp.ncbi.nlm.nih.gov/blast/executables/magicblast/LATEST/ncbi-magicblast-1.6.0-x64-linux.tar.gz
tar -xvzf magicblast.tar.gz && chmod -R 755 ncbi-magicblast-1.6.0/
ln -s ncbi-magicblast-1.6.0/bin/magicblast .

curl -o blast.tar.gz https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.12.0+-x64-linux.tar.gz
tar -xvzf blast.tar.gz && chmod -R 755 ncbi-blast-2.12.0+
ln -s ncbi-blast-2.12.0+/bin/blastdbcmd .

# Download 16S RefSeq database
curl -o 16S_ribosomal_RNA.tar.gz https://ftp.ncbi.nlm.nih.gov/blast/db/16S_ribosomal_RNA.tar.gz
tar -xvzf 16S_ribosomal_RNA.tar.gz
mkdir 16S_ribosomal_RNA/
mv 16S_ribosomal_RNA.* 16S_ribosomal_RNA/
